#!/bin/bash
echo "========================================="
echo "       MY DEVELOPMENT SHORTCUTS"
echo "========================================="
echo ""
echo "🌐 FRONTEND ENVIRONMENTS:"
echo "  frontend-local   - Start frontend with local backend"
echo "  frontend-dev     - Start frontend with dev backend"
echo "  frontend-stage   - Start frontend with stage backend"
echo "  frontend-branch  - Start frontend with branch backend: frontend-branch <name>"
echo "  frontend-status  - Check frontend environment status"
echo ""
echo "🚀 BACKEND ENVIRONMENT:"
echo "  backend-start    - Start backend with current environment and VS Code"
echo ""
echo "📁 PROJECT NAVIGATION:"
echo "  cdpbe        - Jump to ~/code/work/cdp-behind-service"
echo "  cdpui        - Jump to ~/code/work/cdp-ui"
echo "  compose      - Jump to ~/code/work/docker-compose"
echo "  dotfiles     - Jump to ~/dotfiles"
echo "  root         - Jump to home directory"
echo "  work         - Jump to work projects directory"
echo ""
echo "🔀 GIT SHORTCUTS:"
echo "  ga           - git add"
echo "  gb           - git branch"
echo "  gc           - git commit -m"
echo "  gco          - git checkout"
echo "  gd           - git diff"
echo "  gl           - git pull"
echo "  glog         - git log --oneline --graph"
echo "  gp           - git push"
echo "  gs           - git status"
echo "  gcp          - git add, commit, and push"
echo ""
echo "🐳 DOCKER SERVICES:"
echo "  compose           - cd ~/code/work/docker-compose"
echo "  kafka-down        - Stop kafka container"
echo "  kafka-up          - Start kafka container"
echo "  postgres-down     - Stop postgres container"
echo "  postgres-up       - Start postgres container"
echo "  redis-down        - Stop redis container"
echo "  redis-up          - Start redis container"
echo ""
echo "🔑 TOKEN GENERATION:"
echo "  token-local      - Generate token for local environment"
echo "  token-dev        - Generate token for dev environment"
echo "  token-stage      - Generate token for stage environment"
echo "  token-prod       - Generate token for prod environment"
echo ""
echo "📦 NPM SHORTCUTS:"
echo "  nrs          - npm run start"
echo "  nrt          - npm run test"
echo "  nrtu         - npm run test:unit"
echo "  nrdn         - npm run dev:nodb"
echo ""
echo "📋 CLIPBOARD UTILITIES:"
echo "  copy-setup       - Copy full development environment context to clipboard"
echo "  copy-screenshot  - Copy most recent screenshot to clipboard"
echo ""
echo "🛠️  UTILITY SCRIPTS:"
echo "  dev-status       - Check development environment status (-v for verbose)"
echo "  update-shortcuts - Auto-update shortcuts list and push to git"
echo "  add-alias        - Add new alias: add-alias <name> <command>"
echo "  remove-alias     - Remove alias: remove-alias <name>"
echo "  reload           - Reload shell configuration"
echo "  shortcuts        - Display this help menu"
echo "  killport 3000    - Kill process on port 3000"
echo ""
echo "💡 TIPS:"
echo "  - All aliases and functions are defined in ~/.zshrc"
echo "  - Run 'source ~/.zshrc' after editing shell config"
echo "  - Use 'which aliasname' to see what an alias does"
echo "  - Use 'declare -f functionname' to see function definition"
echo "  - Run 'dev-status' for environment health check"
echo ""
echo "Run individual commands to test them out!"
