#!/bin/bash

echo "========================================="
echo "       MY DEVELOPMENT SHORTCUTS"
echo "========================================="
echo ""
echo "📁 PROJECT NAVIGATION:"
echo "  cdpui        - Jump to cdp-ui directory"
echo "  cdpbe        - Jump to cdp-behind-service directory"
echo "  work        - Jump to work directory"
echo "  compose        - Jump to docker-compose directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  token-local        - Jump to admin token --env local directory"
echo "  token-dev        - Jump to admin token --env dev directory"
echo "  token-stage        - Jump to admin token --env stage directory"
echo "  token-prod        - Jump to admin token --env prod directory"
echo "  dotfiles        - Jump to dotfiles directory"
echo "  gs           - git status"
echo "  ga           - git add"
echo "  gc           - git commit -m"
echo "  gp           - git push"
echo "  gl           - git pull"
echo "  gco           - git checkout"
echo "  gb           - git branch"
echo "  gd           - git diff"
echo "  glog           - git log --oneline --graph"
echo "  gcp 'msg'    - git add . && git commit -m 'msg' && git push (all-in-one)"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  token-local      - Generate token for local environment"
echo "  token-dev      - Generate token for dev environment"
echo "  token-stage      - Generate token for stage environment"
echo "  token-prod      - Generate token for prod environment"
echo "  nrs          - npm run start"
echo "  nrt          - npm run test"
echo "  nrtu          - npm run test:unit"
echo "  nrdn          - npm run dev:nodb"
echo "  update-shortcuts - Auto-update shortcuts list and push to git"
echo "  shortcuts    - Display this help menu"
echo "  reload       - Reload shell configuration"
echo "  killport 3000 - Kill process on port 3000"

echo ""
echo "🔀 GIT SHORTCUTS:"
echo "  cdpui        - Jump to cdp-ui directory"
echo "  cdpbe        - Jump to cdp-behind-service directory"
echo "  work        - Jump to work directory"
echo "  compose        - Jump to docker-compose directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  token-local        - Jump to admin token --env local directory"
echo "  token-dev        - Jump to admin token --env dev directory"
echo "  token-stage        - Jump to admin token --env stage directory"
echo "  token-prod        - Jump to admin token --env prod directory"
echo "  dotfiles        - Jump to dotfiles directory"
echo "  gs           - git status"
echo "  ga           - git add"
echo "  gc           - git commit -m"
echo "  gp           - git push"
echo "  gl           - git pull"
echo "  gco           - git checkout"
echo "  gb           - git branch"
echo "  gd           - git diff"
echo "  glog           - git log --oneline --graph"
echo "  gcp 'msg'    - git add . && git commit -m 'msg' && git push (all-in-one)"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  token-local      - Generate token for local environment"
echo "  token-dev      - Generate token for dev environment"
echo "  token-stage      - Generate token for stage environment"
echo "  token-prod      - Generate token for prod environment"
echo "  nrs          - npm run start"
echo "  nrt          - npm run test"
echo "  nrtu          - npm run test:unit"
echo "  nrdn          - npm run dev:nodb"
echo "  update-shortcuts - Auto-update shortcuts list and push to git"
echo "  shortcuts    - Display this help menu"
echo "  reload       - Reload shell configuration"
echo "  killport 3000 - Kill process on port 3000"

echo ""
echo "🐳 DOCKER SERVICES:"
echo "  cdpui        - Jump to cdp-ui directory"
echo "  cdpbe        - Jump to cdp-behind-service directory"
echo "  work        - Jump to work directory"
echo "  compose        - Jump to docker-compose directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  token-local        - Jump to admin token --env local directory"
echo "  token-dev        - Jump to admin token --env dev directory"
echo "  token-stage        - Jump to admin token --env stage directory"
echo "  token-prod        - Jump to admin token --env prod directory"
echo "  dotfiles        - Jump to dotfiles directory"
echo "  gs           - git status"
echo "  ga           - git add"
echo "  gc           - git commit -m"
echo "  gp           - git push"
echo "  gl           - git pull"
echo "  gco           - git checkout"
echo "  gb           - git branch"
echo "  gd           - git diff"
echo "  glog           - git log --oneline --graph"
echo "  gcp 'msg'    - git add . && git commit -m 'msg' && git push (all-in-one)"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  token-local      - Generate token for local environment"
echo "  token-dev      - Generate token for dev environment"
echo "  token-stage      - Generate token for stage environment"
echo "  token-prod      - Generate token for prod environment"
echo "  nrs          - npm run start"
echo "  nrt          - npm run test"
echo "  nrtu          - npm run test:unit"
echo "  nrdn          - npm run dev:nodb"
echo "  update-shortcuts - Auto-update shortcuts list and push to git"
echo "  shortcuts    - Display this help menu"
echo "  reload       - Reload shell configuration"
echo "  killport 3000 - Kill process on port 3000"

echo ""
echo "🔑 TOKEN GENERATION:"
echo "  cdpui        - Jump to cdp-ui directory"
echo "  cdpbe        - Jump to cdp-behind-service directory"
echo "  work        - Jump to work directory"
echo "  compose        - Jump to docker-compose directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  token-local        - Jump to admin token --env local directory"
echo "  token-dev        - Jump to admin token --env dev directory"
echo "  token-stage        - Jump to admin token --env stage directory"
echo "  token-prod        - Jump to admin token --env prod directory"
echo "  dotfiles        - Jump to dotfiles directory"
echo "  gs           - git status"
echo "  ga           - git add"
echo "  gc           - git commit -m"
echo "  gp           - git push"
echo "  gl           - git pull"
echo "  gco           - git checkout"
echo "  gb           - git branch"
echo "  gd           - git diff"
echo "  glog           - git log --oneline --graph"
echo "  gcp 'msg'    - git add . && git commit -m 'msg' && git push (all-in-one)"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  token-local      - Generate token for local environment"
echo "  token-dev      - Generate token for dev environment"
echo "  token-stage      - Generate token for stage environment"
echo "  token-prod      - Generate token for prod environment"
echo "  nrs          - npm run start"
echo "  nrt          - npm run test"
echo "  nrtu          - npm run test:unit"
echo "  nrdn          - npm run dev:nodb"
echo "  update-shortcuts - Auto-update shortcuts list and push to git"
echo "  shortcuts    - Display this help menu"
echo "  reload       - Reload shell configuration"
echo "  killport 3000 - Kill process on port 3000"

echo ""
echo "📦 NPM SHORTCUTS:"
echo "  cdpui        - Jump to cdp-ui directory"
echo "  cdpbe        - Jump to cdp-behind-service directory"
echo "  work        - Jump to work directory"
echo "  compose        - Jump to docker-compose directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  token-local        - Jump to admin token --env local directory"
echo "  token-dev        - Jump to admin token --env dev directory"
echo "  token-stage        - Jump to admin token --env stage directory"
echo "  token-prod        - Jump to admin token --env prod directory"
echo "  dotfiles        - Jump to dotfiles directory"
echo "  gs           - git status"
echo "  ga           - git add"
echo "  gc           - git commit -m"
echo "  gp           - git push"
echo "  gl           - git pull"
echo "  gco           - git checkout"
echo "  gb           - git branch"
echo "  gd           - git diff"
echo "  glog           - git log --oneline --graph"
echo "  gcp 'msg'    - git add . && git commit -m 'msg' && git push (all-in-one)"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  token-local      - Generate token for local environment"
echo "  token-dev      - Generate token for dev environment"
echo "  token-stage      - Generate token for stage environment"
echo "  token-prod      - Generate token for prod environment"
echo "  nrs          - npm run start"
echo "  nrt          - npm run test"
echo "  nrtu          - npm run test:unit"
echo "  nrdn          - npm run dev:nodb"
echo "  update-shortcuts - Auto-update shortcuts list and push to git"
echo "  shortcuts    - Display this help menu"
echo "  reload       - Reload shell configuration"
echo "  killport 3000 - Kill process on port 3000"

echo ""
echo "🛠️  UTILITY SCRIPTS:"
echo "  cdpui        - Jump to cdp-ui directory"
echo "  cdpbe        - Jump to cdp-behind-service directory"
echo "  work        - Jump to work directory"
echo "  compose        - Jump to docker-compose directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  redis-up        - Jump to Redis && docker-compose up -d directory"
echo "  redis-down        - Jump to Redis && docker-compose down directory"
echo "  postgres-up        - Jump to Postgres && docker-compose up -d directory"
echo "  postgres-down        - Jump to Postgres && docker-compose down directory"
echo "  kafka-up        - Jump to Kafka && docker-compose up -d directory"
echo "  kafka-down        - Jump to Kafka && docker-compose down directory"
echo "  token-local        - Jump to admin token --env local directory"
echo "  token-dev        - Jump to admin token --env dev directory"
echo "  token-stage        - Jump to admin token --env stage directory"
echo "  token-prod        - Jump to admin token --env prod directory"
echo "  dotfiles        - Jump to dotfiles directory"
echo "  gs           - git status"
echo "  ga           - git add"
echo "  gc           - git commit -m"
echo "  gp           - git push"
echo "  gl           - git pull"
echo "  gco           - git checkout"
echo "  gb           - git branch"
echo "  gd           - git diff"
echo "  glog           - git log --oneline --graph"
echo "  gcp 'msg'    - git add . && git commit -m 'msg' && git push (all-in-one)"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  redis-up         - Start redis container"
echo "  redis-down       - Stop redis container"
echo "  postgres-up         - Start postgres container"
echo "  postgres-down       - Stop postgres container"
echo "  kafka-up         - Start kafka container"
echo "  kafka-down       - Stop kafka container"
echo "  dev-services-up         - Start dev-services container"
echo "  dev-services-down       - Stop dev-services container"
echo "  token-local      - Generate token for local environment"
echo "  token-dev      - Generate token for dev environment"
echo "  token-stage      - Generate token for stage environment"
echo "  token-prod      - Generate token for prod environment"
echo "  nrs          - npm run start"
echo "  nrt          - npm run test"
echo "  nrtu          - npm run test:unit"
echo "  nrdn          - npm run dev:nodb"
echo "  update-shortcuts - Auto-update shortcuts list and push to git"
echo "  shortcuts    - Display this help menu"
echo "  reload       - Reload shell configuration"
echo "  killport 3000 - Kill process on port 3000"

echo ""
echo "💡 TIPS:"
echo "  - All aliases are defined in ~/.zshrc"
echo "  - Run 'source ~/.zshrc' after editing shell config"
echo "  - Use 'which aliasname' to see what an alias does"
echo ""

echo "🔍 CURRENT STATUS:"
if [ -n "$NPM_TOKEN" ]; then
    echo "  ✅ NPM_TOKEN is set and ready"
else
    echo "  ❌ NPM_TOKEN not found"
fi

if command -v volta >/dev/null 2>&1; then
    echo "  ✅ Volta (Node manager) installed: $(volta --version)"
else
    echo "  ❌ Volta not found"
fi

if command -v code >/dev/null 2>&1; then
    echo "  ✅ VS Code CLI available"
else
    echo "  ❌ VS Code CLI not available"
fi

if command -v docker >/dev/null 2>&1; then
    echo "  ✅ Docker installed: $(docker --version | cut -d' ' -f3 | cut -d',' -f1)"
else
    echo "  ❌ Docker not installed"
fi

echo ""
echo "Run individual commands to test them out!"
